spring:
  messages:
    basename=messages,config.i18n.messages
  profiles:
    active: production
    group:
      devel[0] : devel-ws
      devel[1] : devel-db

app:
  lesson: LESSON 1

lesson:
  author: alessandro.vizzarro@aesys.tech
  welcome-message: Welcome to ${app.lesson} !!!

my:
  service:
    name: MyService
    version: v1
    enabled: true
    token: djfoijfw4453nfjrejotj4534df354==

print-something:
  service-qualifier-key: printService
  service1:
    value: Ciao Alessandro!
  service2:
    value: Ciao Francesco!

