spring:
  profiles:
    active: devel

app:
  lesson: LESSON 1

lesson:
  author: alessandro.vizzarro@aesys.tech
  welcome-message: Welcome to ${app.lesson} !!!

my:
  service:
    name: MyService
    version: v1
    enabled: true
    token: djfoijfw4453nfjrejotj4534df354==

print-something:
  service-qualifier-key: printService
  service1:
    value: Ciao Alessandro!
  service2:
    value: Ciao Francesco!