app:
  lesson: LESSON 1

lesson:
  author: alessandro.vizzarro@aesys.tech
  welcome-message: Welcome to Lesson 1 !!!

print-something:
  service-qualifier-key: Print1
  service1:
    value: Ciao Alessandro!
  service2:
    value: Ciao Francesco!
